refactor: rename `_completion_loader => _comp_complete_load`

diff --git a/bash_completion b/bash_completion
--- a/bash_completion
+++ b/bash_completion
@@ -2658,7 +2658,7 @@ _comp_command_offset()
         # If still nothing, just load it for the basename
         if [[ ! $cspec ]]; then
             compcmd=${cmd##*/}
-            _completion_loader "$compcmd"
+            _comp_load -D -- "$compcmd"
             cspec=$(complete -p "$compcmd" 2>/dev/null)
         fi
 
@@ -2947,7 +2947,7 @@ _comp__init_install_xspec '!@(*.@(ks|jks|jceks|p12|pfx|bks|ubr|gkr|cer|crt|cert|
 _comp__init_install_xspec '!*.@(mp[234c]|og[ag]|@(fl|a)ac|m4[abp]|spx|tta|w?(a)v|wma|aif?(f)|asf|ape)' kid3 kid3-qt
 unset -f _comp__init_install_xspec
 
-# Minimal completion to use as fallback in _completion_loader.
+# Minimal completion to use as fallback in _comp_complete_load.
 # TODO:API: rename per conventions
 _minimal()
 {
@@ -2962,6 +2962,19 @@ complete -F _minimal ''
 # @since 2.12
 _comp_load()
 {
+    local flag_fallback_default="" IFS=$' \t\n'
+    local OPTIND=1 OPTARG="" OPTERR=0 opt
+    while getopts ':D' opt "$@"; do
+        case $opt in
+            D) flag_fallback_default=set ;;
+            *)
+                echo "bash_completion: $FUNCNAME: usage error" >&2
+                return 2
+                ;;
+        esac
+    done
+    shift "$((OPTIND - 1))"
+
     local cmd=$1 cmdname=${1##*/} dir compfile
     local -a paths
     [[ $cmdname ]] || return 1
@@ -3071,22 +3084,25 @@ _comp_load()
     [[ -v _comp_xspecs[$cmdname] || -v _xspecs[$cmdname] ]] &&
         complete -F _filedir_xspec "$cmdname" "$backslash$cmdname" && return 0
 
+    if [[ $flag_fallback_default ]]; then
+        complete -F _minimal -- "$origcmd" && return 0
+    fi
+
     return 1
 }
 
 # set up dynamic completion loading
-# TODO:API: rename per conventions
-_completion_loader()
+# @since 2.12
+_comp_complete_load()
 {
     # $1=_EmptycmD_ already for empty cmds in bash 4.3, set to it for earlier
     local cmd=${1:-_EmptycmD_}
 
-    _comp_load "$cmd" && return 124
-
-    # Need to define *something*, otherwise there will be no completion at all.
-    complete -F _minimal -- "$cmd" && return 124
+    # Pass -D to define *something*, or otherwise there will be no completion
+    # at all.
+    _comp_load -D -- "$cmd" && return 124
 } &&
-    complete -D -F _completion_loader
+    complete -D -F _comp_complete_load
 
 # Function for loading and calling functions from dynamically loaded
 # completion files that may not have been sourced yet.
