_known_hosts_real: improve invalid pattern handling for host-exclusion-patterns
Previously, when any pattern was invalid, no completions would have resulted at
all and `grep`’s error message (which was the only indicator about where the
problem lies) was discarded.

This commit changes the following:
- `grep`’s error message is no longer discarded to give a hint where in the
  problem the error is.
- An additional error message is printed to standard error in order to indicate
  what even causes the problem.
- The previous completions are assigned to the `COMPREPLY` array, thereby
  effectively “just” disabling host-exclusion-patterns.

Signed-off-by: Christoph Anton Mitterer <mail@christoph.anton.mitterer.name>

diff --git a/bash_completion b/bash_completion
--- a/bash_completion
+++ b/bash_completion
@@ -1978,7 +1978,7 @@ _known_hosts_real()
         local host_exclusion_pattern="$( printf '%s' "${BASH_COMPLETION_HOST_EXCLUSION_PATTERN-}"  |  command -p awk 1 - "${BASH_COMPLETION_HOST_EXCLUSION_PATTERN_FILES[@]-}" 2>/dev/null  |  grep -E -v '^[[:space:]]*(#|$)'  ||  true )"
 
         if [ -n "${host_exclusion_pattern}" ]; then
-            COMPREPLY=( $(  printf '%s\n' "${COMPREPLY[@]}"  |  command -p grep ${re_language} -v "${host_exclusion_pattern}" 2>/dev/null  ||  true  ) )
+            COMPREPLY=( $(  printf '%s\n' "${COMPREPLY[@]}"  |  command -p grep ${re_language} -v "${host_exclusion_pattern}"  ||  { printf '%s\n' "${COMPREPLY[@]}"; printf 'bash-completion: host-exclusion-patterns disabled because of invalid pattern.\n' >&2; }  ) )
         fi
     fi
 
