feat(_comp_compgen_filedir): support "filedir -X"
Co-authored-by: Ville Skyttä <ville.skytta@iki.fi>

diff --git a/bash_completion b/bash_completion
--- a/bash_completion
+++ b/bash_completion
@@ -1289,11 +1289,14 @@ _comp_quote_compgen()
 #           Ignored with `-d`.
 # OPTIONS
 #   -d      Complete only on directories
-
 #   -f      Perform `compopt -o filenames` modifications manually.  This
 #           suffixes a slash to a directory name.  When "-C <dir>" or "-P
 #           <prefix>" is specified to the "_comp_compgen" call, this option
 #           is automatically turned on.
+#   -X PATTERN
+#           @since 2.18 Specify the filename pattern to exclude, or the
+#           filename pattern to include prefixed by "!".  When this option is
+#           specified, $1 should be empty or not specified.
 # @return 0 if at least one completion is generated, or 1 otherwise.
 #
 # @since 2.12
@@ -1302,7 +1305,7 @@ _comp_compgen_filedir()
     _comp_compgen_tilde && return
 
     local -a toks
-    local _dir="" _filenames=""
+    local _dir="" _filenames="" _xspec=""
     if [[ ${_comp_compgen__dir-} || ${_comp_compgen__prefix-} ]]; then
         # When "-C <dir>" or "-P <prefix>" is specified, the working directory
         # does not contain the generated candidates as filenames.  In the case
@@ -1317,10 +1320,11 @@ _comp_compgen_filedir()
     fi
 
     local OPTIND=1 OPTARG="" OPTERR=0 _opt
-    while getopts ":df" _opt "$@"; do
+    while getopts ":dfX:" _opt "$@"; do
         case $_opt in
             d) _dir=set ;;
             f) _filenames=set ;;
+            X) _xspec=$OPTARG ;;
             *)
                 printf "bash_completion: %s: usage error\n" "$FUNCNAME" >&2
                 return 2
@@ -1329,6 +1333,10 @@ _comp_compgen_filedir()
     done
     shift "$((OPTIND - 1))"
     local _arg=${1-}
+    if [[ $_xspec && $_arg ]]; then
+        printf 'bash_completion: %s: "-X xspec" and "$1" cannot be specified simultaneously\n' "$FUNCNAME" >&2
+        return 2
+    fi
 
     if [[ $_dir ]]; then
         _comp_compgen -v toks -- -d
@@ -1344,7 +1352,7 @@ _comp_compgen_filedir()
         # Munge xspec to contain uppercase version too
         # https://lists.gnu.org/archive/html/bug-bash/2010-09/msg00036.html
         # news://news.gmane.io/4C940E1C.1010304@case.edu
-        local _xspec=${_arg:+"!*.@($_arg|${_arg^^})"}
+        [[ $_xspec ]] || _xspec=${_arg:+"!*.@($_arg|${_arg^^})"}
 
         local _opts=(-f -X "$_xspec")
         # Use plusdirs to get dir completions if we have a xspec; if we don't,
@@ -1543,20 +1551,7 @@ _comp_variable_assignments()
 
     case $prev in
         TZ)
-            cur=/usr/share/zoneinfo/$cur
-            _comp_compgen_filedir
-            if ((${#COMPREPLY[@]})); then
-                for i in "${!COMPREPLY[@]}"; do
-                    if [[ ${COMPREPLY[i]} == *.tab ]]; then
-                        unset -v 'COMPREPLY[i]'
-                        continue
-                    elif [[ -d ${COMPREPLY[i]} ]]; then
-                        COMPREPLY[i]+=/
-                        compopt -o nospace
-                    fi
-                    COMPREPLY[i]=${COMPREPLY[i]#/usr/share/zoneinfo/}
-                done
-            fi
+            _comp_compgen -C /usr/share/zoneinfo filedir -fX '*.tab'
             ;;
         TERM)
             _comp_compgen_terms
