refactor(_command_offset): refactor the retry loop by 124

diff --git a/bash_completion b/bash_completion
--- a/bash_completion
+++ b/bash_completion
@@ -2073,48 +2073,55 @@ _command_offset()
             cspec=$(complete -p "$compcmd" 2>/dev/null)
         fi
 
-        if [[ -n $cspec ]]; then
-            for ((i = 0; i <= 1; i++)); do
-                if [[ ${cspec#* -F } != "$cspec" ]]; then
-                    # complete -F <function>
-
-                    # get function name
-                    local func=${cspec#*-F }
-                    func=${func%% *}
-
-                    if ((${#COMP_WORDS[@]} >= 2)); then
-                        $func "$cmd" "${COMP_WORDS[-1]}" "${COMP_WORDS[-2]}"
-                    else
-                        $func "$cmd" "${COMP_WORDS[-1]}"
-                    fi
-
-                    # restart completion (once) if function exited with 124
-                    if (($? == 124 && i == 0)); then
-                        cspec=$(complete -p "$compcmd" 2>/dev/null)
-                        [[ -n $cspec ]] && continue
-                    fi
-
-                    # restore initial compopts
-                    local opt
-                    while [[ $cspec == *" -o "* ]]; do
-                        # FIXME: should we take "+o opt" into account?
-                        cspec=${cspec#*-o }
-                        opt=${cspec%% *}
-                        compopt -o $opt
-                        cspec=${cspec#"$opt"}
-                    done
-                else
-                    cspec=${cspec#complete}
-                    cspec=${cspec%%"$compcmd"}
-                    COMPREPLY=($(eval compgen "$cspec" -- '$cur'))
+        local retry_count=0
+        while true; do # loop for the retry request by status 124
+            if [[ ! $cspec ]]; then
+                if ((${#COMPREPLY[@]} == 0)); then
+                    # XXX will probably never happen as long as completion loader loads
+                    #     *something* for every command thrown at it ($cspec != empty)
+                    _minimal
                 fi
-                break
-            done
-        elif ((${#COMPREPLY[@]} == 0)); then
-            # XXX will probably never happen as long as completion loader loads
-            #     *something* for every command thrown at it ($cspec != empty)
-            _minimal
-        fi
+            elif [[ $cspec == *' -F '* ]]; then
+                # complete -F <function>
+
+                # get function name
+                local func=${cspec#* -F }
+                func=${func%% *}
+
+                if ((${#COMP_WORDS[@]} >= 2)); then
+                    $func "$cmd" "${COMP_WORDS[-1]}" "${COMP_WORDS[-2]}"
+                else
+                    $func "$cmd" "${COMP_WORDS[-1]}"
+                fi
+
+                # restart completion (once) if function exited with 124
+                if (($? == 124 && retry_count++ == 0)); then
+                    cspec=$(complete -p "$compcmd" 2>/dev/null)
+
+                    # Note: When completion spec is removed after 124, we do
+                    # not generate any completions including the default ones.
+                    # This is the behavior of the original Bash progcomp.
+                    [[ -n $cspec ]] || break
+
+                    continue
+                fi
+
+                # restore initial compopts
+                local opt
+                while [[ $cspec == *" -o "* ]]; do
+                    # FIXME: should we take "+o opt" into account?
+                    cspec=${cspec#*-o }
+                    opt=${cspec%% *}
+                    compopt -o $opt
+                    cspec=${cspec#"$opt"}
+                done
+            else
+                cspec=${cspec#complete}
+                cspec=${cspec%%"$compcmd"}
+                COMPREPLY=($(eval compgen "$cspec" -- '$cur'))
+            fi
+            break
+        done
     fi
 }
 complete -F _command aoss command "do" else eval exec ltrace nice nohup padsp \
