refactor(_comp_deprecate_func): add version parameter
Making it the first one to make forgetting or faking it harder.

https://github.com/scop/bash-completion/issues/893

diff --git a/bash_completion b/bash_completion
--- a/bash_completion
+++ b/bash_completion
@@ -41,18 +41,23 @@ fi
 shopt -s extglob progcomp
 
 # Declare a compatibility function name
-# @param $1 Old function name
-# @param $2 New function name
+# @param $1 Version of bash-completion where the deprecation occurred
+# @param $2 Old function name
+# @param $3 New function name
 _comp_deprecate_func()
 {
-    if [[ $1 != [a-zA-Z_]*([a-zA-Z_0-9]) ]]; then
-        printf 'bash_completion: %s: %s\n' "$FUNCNAME" "\$1: invalid function name '$1'" >&2
-        return 2
-    elif [[ $2 != [a-zA-Z_]*([a-zA-Z_0-9]) ]]; then
-        printf 'bash_completion: %s: %s\n' "$FUNCNAME" "\$2: invalid function name '$2'" >&2
+    if (($# != 3)); then
+        printf 'bash_completion: %s: usage: %s OLD_NAME NEW_NAME DEPRECATION_VERSION\n' "$FUNCNAME" "$FUNCNAME"
         return 2
     fi
-    eval -- "$1() { $2 \"\$@\"; }"
+    if [[ $2 != [a-zA-Z_]*([a-zA-Z_0-9]) ]]; then
+        printf 'bash_completion: %s: %s\n' "$FUNCNAME" "\$2: invalid function name '$1'" >&2
+        return 2
+    elif [[ $3 != [a-zA-Z_]*([a-zA-Z_0-9]) ]]; then
+        printf 'bash_completion: %s: %s\n' "$FUNCNAME" "\$3: invalid function name '$2'" >&2
+        return 2
+    fi
+    eval -- "$2() { $3 \"\$@\"; }"
 }
 
 # A lot of the following one-liners were taken directly from the
